"""
backend/app/database/seed_historical_events.py
-----------------------------------------------
Deterministic Seed Pool for Historical Event Observations.

DEMO / HACKATHON NOTICE:
The records generated by this module represent DEMO / SEEDED HISTORICAL EVENT
OBSERVATIONS created specifically for offline, deterministic demonstration and testing of the
Historical Event Matcher, Event Statistics, Wilson 95% Confidence Interval,
Confidence Engine, and Decision Engine pipeline.

These observations are synthetic demo fixtures designed to showcase end-to-end
statistical reasoning and MUST NOT be used as real investment advice or actual
production historical market research.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import List

from backend.app.services.event_study import EventStudyResult
from backend.app.services.historical_matcher import HistoricalEventFeatures

logger = logging.getLogger(__name__)

DEMO_DATASET_LABEL = "DEMO / SEEDED HISTORICAL EVENT OBSERVATIONS"


def generate_seeded_historical_events() -> List[HistoricalEventFeatures]:
    """
    Generate a deterministic seed pool of historical event observations.

    Includes 45+ observations per major event class across sectors (IT, AUTOMOBILE,
    FINANCE, PHARMA) and market cap buckets (LARGE, MID, SMALL) with realistic,
    deterministic 1D, 3D, and 5D excess returns.
    """
    events: List[HistoricalEventFeatures] = []

    # ---------------------------------------------------------------------------
    # 1. EARNINGS_RELEASE (Positive Beats) — 45 Observations
    # ---------------------------------------------------------------------------
    it_large_tickers = ["TCS", "INFY", "WIPRO", "HCLTECH"]
    for i in range(45):
        news_id = f"DEMO-EARN-POS-{i+1:03d}"
        symbol = it_large_tickers[i % len(it_large_tickers)]
        # Deterministic excess returns around +4.5% 1D, +6.2% 3D, +7.8% 5D
        r1d = round(0.035 + (i % 5) * 0.005, 4)
        r3d = round(r1d + 0.015 + (i % 3) * 0.003, 4)
        r5d = round(r3d + 0.015 + (i % 4) * 0.004, 4)

        es = EventStudyResult(
            news_id=news_id,
            symbol=symbol,
            exchange="NSE",
            event_date=datetime(2024, 1, (i % 28) + 1, 10, 0, tzinfo=timezone.utc),
            excess_return_1d=r1d,
            excess_return_3d=r3d,
            excess_return_5d=r5d,
        )

        events.append(
            HistoricalEventFeatures(
                news_id=news_id,
                symbol=symbol,
                event_type="EARNINGS_RELEASE",
                sentiment="positive",
                sector="IT",
                market_cap_bucket="LARGE",
                event_date=datetime(2024, 1, (i % 28) + 1, 10, 0, tzinfo=timezone.utc),
                event_study=es,
            )
        )

    # ---------------------------------------------------------------------------
    # 2. MAJOR_CONTRACT (Positive Contract Wins) — 45 Observations
    # ---------------------------------------------------------------------------
    auto_large_tickers = ["TATAMOTORS", "MARUTI", "M&M", "BAJAJ-AUTO"]
    for i in range(45):
        news_id = f"DEMO-CONTRACT-POS-{i+1:03d}"
        symbol = auto_large_tickers[i % len(auto_large_tickers)]
        # Deterministic excess returns around +3.2% 1D, +4.8% 3D, +6.0% 5D
        r1d = round(0.025 + (i % 5) * 0.004, 4)
        r3d = round(r1d + 0.012 + (i % 3) * 0.003, 4)
        r5d = round(r3d + 0.012 + (i % 4) * 0.003, 4)

        es = EventStudyResult(
            news_id=news_id,
            symbol=symbol,
            exchange="NSE",
            event_date=datetime(2024, 2, (i % 28) + 1, 11, 0, tzinfo=timezone.utc),
            excess_return_1d=r1d,
            excess_return_3d=r3d,
            excess_return_5d=r5d,
        )

        events.append(
            HistoricalEventFeatures(
                news_id=news_id,
                symbol=symbol,
                event_type="MAJOR_CONTRACT",
                sentiment="positive",
                sector="AUTOMOBILE",
                market_cap_bucket="LARGE",
                event_date=datetime(2024, 2, (i % 28) + 1, 11, 0, tzinfo=timezone.utc),
                event_study=es,
            )
        )

    # ---------------------------------------------------------------------------
    # 3. PRODUCT_RECALL (Negative Recalls) — 45 Observations
    # ---------------------------------------------------------------------------
    for i in range(45):
        news_id = f"DEMO-RECALL-NEG-{i+1:03d}"
        symbol = auto_large_tickers[i % len(auto_large_tickers)]
        # Deterministic excess returns around -5.5% 1D, -7.2% 3D, -9.0% 5D
        r1d = round(-0.040 - (i % 5) * 0.006, 4)
        r3d = round(r1d - 0.018 - (i % 3) * 0.004, 4)
        r5d = round(r3d - 0.018 - (i % 4) * 0.004, 4)

        es = EventStudyResult(
            news_id=news_id,
            symbol=symbol,
            exchange="NSE",
            event_date=datetime(2024, 3, (i % 28) + 1, 9, 30, tzinfo=timezone.utc),
            excess_return_1d=r1d,
            excess_return_3d=r3d,
            excess_return_5d=r5d,
        )

        events.append(
            HistoricalEventFeatures(
                news_id=news_id,
                symbol=symbol,
                event_type="PRODUCT_RECALL",
                sentiment="negative",
                sector="AUTOMOBILE",
                market_cap_bucket="LARGE",
                event_date=datetime(2024, 3, (i % 28) + 1, 9, 30, tzinfo=timezone.utc),
                event_study=es,
            )
        )

    # ---------------------------------------------------------------------------
    # 4. MANAGEMENT_CHANGE — 45 Observations
    # ---------------------------------------------------------------------------
    fin_large_tickers = ["HDFCBANK", "ICICIBANK", "SBIN", "KOTAKBANK"]
    for i in range(45):
        news_id = f"DEMO-MGMT-NEG-{i+1:03d}"
        symbol = fin_large_tickers[i % len(fin_large_tickers)]
        # Mixed/Negative excess returns around -2.5% 1D, -3.5% 3D, -4.5% 5D
        r1d = round(-0.015 - (i % 4) * 0.005, 4)
        r3d = round(r1d - 0.010 - (i % 3) * 0.003, 4)
        r5d = round(r3d - 0.010 - (i % 4) * 0.003, 4)

        es = EventStudyResult(
            news_id=news_id,
            symbol=symbol,
            exchange="NSE",
            event_date=datetime(2024, 4, (i % 28) + 1, 14, 0, tzinfo=timezone.utc),
            excess_return_1d=r1d,
            excess_return_3d=r3d,
            excess_return_5d=r5d,
        )

        events.append(
            HistoricalEventFeatures(
                news_id=news_id,
                symbol=symbol,
                event_type="MANAGEMENT_CHANGE",
                sentiment="negative",
                sector="FINANCE",
                market_cap_bucket="LARGE",
                event_date=datetime(2024, 4, (i % 28) + 1, 14, 0, tzinfo=timezone.utc),
                event_study=es,
            )
        )

    # ---------------------------------------------------------------------------
    # 5. GENERAL_NEWS — 45 Observations
    # ---------------------------------------------------------------------------
    for i in range(45):
        news_id = f"DEMO-GENERAL-POS-{i+1:03d}"
        symbol = it_large_tickers[i % len(it_large_tickers)]
        # Positive general news excess returns around +3.0% 1D, +4.2% 3D, +5.5% 5D
        r1d = round(0.020 + (i % 5) * 0.004, 4)
        r3d = round(r1d + 0.010 + (i % 3) * 0.003, 4)
        r5d = round(r3d + 0.010 + (i % 4) * 0.003, 4)

        es = EventStudyResult(
            news_id=news_id,
            symbol=symbol,
            exchange="NSE",
            event_date=datetime(2024, 5, (i % 28) + 1, 12, 0, tzinfo=timezone.utc),
            excess_return_1d=r1d,
            excess_return_3d=r3d,
            excess_return_5d=r5d,
        )

        events.append(
            HistoricalEventFeatures(
                news_id=news_id,
                symbol=symbol,
                event_type="GENERAL_NEWS",
                sentiment="positive" if i % 6 != 0 else "neutral",
                sector="IT",
                market_cap_bucket="LARGE",
                event_date=datetime(2024, 5, (i % 28) + 1, 12, 0, tzinfo=timezone.utc),
                event_study=es,
            )
        )

    return events


# Singleton cached instance of the seed pool
_SEEDED_HISTORICAL_EVENTS_CACHE: List[HistoricalEventFeatures] = []


def get_seeded_historical_events() -> List[HistoricalEventFeatures]:
    """Return cached seed pool of demo historical event observations."""
    global _SEEDED_HISTORICAL_EVENTS_CACHE
    if not _SEEDED_HISTORICAL_EVENTS_CACHE:
        _SEEDED_HISTORICAL_EVENTS_CACHE = generate_seeded_historical_events()
        logger.info(
            "Initialised demo seed pool with %d historical event observations.",
            len(_SEEDED_HISTORICAL_EVENTS_CACHE),
        )
    return _SEEDED_HISTORICAL_EVENTS_CACHE
